name: CycleTLS Issue
description: Please use this to report any issue
labels: [triage]
assignees:
  - Danny-Dasilva
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a issue with CycleTLS
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: Please describe the current and expected behaviour, and attach all files/info needed to reproduce the issue if applicable.
#       placeholder: Describe the issue here!
#       value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue would you like to report?
      multiple: true
      options:
        - Bug
        - Build/Install
        - Performance
        - Support
        - Feature Request
        - Documentation Request
        - Others
  - type: dropdown
    id: Operating-System
    attributes:
      label: Operating System
      description: What OS are you seeing the issue in? If you don't see your OS listed, please provide more details in the "Description" section above.
      multiple: true
      options:
        - Windows 10
        - Linux
        - Mac OS
        - Other
  - type: dropdown
    id: Node-Version
    attributes:
      label: Node Version
      description: What Node version are you using? If "other", please provide more details in the "Description" section above.
      multiple: false
      options:
        - Node 16.x
        - Node 18.x
        - Node 20.x
        - Node 22.x
        - Other
  - type: dropdown
    id: Go-Version
    attributes:
      label: Golang Version
      description: What Golang version are you using? If "other", please provide more details in the "Description" section above.
      multiple: false
      options:
        - Go 14.x
        - Go 15.x
        - Go 16.x
        - Go 17.x
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
