name: "🚨 🚀 🟢 Npm Test Publish Package"

on: [pull_request]

jobs:
  release:
    name: Test Npm Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        go-version: ['1.25']
    steps:
      - uses: actions/checkout@v4
      - name: 🟢 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: ./cycletls/go.sum
      - name: Install golang dependencies
        run: cd cycletls && go mod download && go mod verify

      - name: Install npm dependencies
        run: npm ci --unsafe-perm

        working-directory: ./

      - name: 🚀 publish
        run: npm publish --dry-run
        working-directory: ./
